<a href="https://colab.research.google.com/github/sidharth-ds/Natural-Language-Processing-projects/blob/main/spelling_correction_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import pandas as pd
from textblob import TextBlob
import re
import string

In [95]:
df = pd.read_csv("/content/spell.csv", header=None)
df

                                               0
0      Hokkaido is in the northrn part of Japan.
1      Hokkaido is in the northrn part of Japan.
2       How about going to the movie on Satrday?
3       How about going to the movie on Satrday?
4    How am I goiing to protect my children now?
..                                           ...
638  I have got my guitar in the tunk of my car.
639  I have got plenty more whre that came from.
640  I have just taled to Tom about that matter.
641  I have known her for more than twnty years.
642  I have livd here for more than three years.

[643 rows x 1 columns]

In [96]:
df = df.drop_duplicates()
df.shape

(482, 1)

In [97]:
def clean(text):
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
  
    return text

df["processed"] = df[0].apply(clean)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [98]:
df

,0,processed
0,Hokkaido is in the northrn part of Japan.,hokkaido is in the northrn part of japan
2,How about going to the movie on Satrday?,how about going to the movie on satrday
4,How am I goiing to protect my children now?,how am i goiing to protect my children now
5,How are you getting along in your neww job?,how are you getting along in your neww job
6,How are you getting along with your steudy?,how are you getting along with your steudy
...,...,...
638,I have got my guitar in the tunk of my car.,i have got my guitar in the tunk of my car
639,I have got plenty more whre that came from.,i have got plenty more whre that came from
640,I have just taled to Tom about that matter.,i have just taled to tom about that matter
641,I have known her for more than twnty years.,i have known her for more than twnty years
642,I have livd here for more than three years.,i have livd here for more than three years

In [99]:
def correction(x):
  ans = TextBlob(x)
  return "".join(ans.correct())

In [100]:
df['corrected'] = df['processed'].apply(correction)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [101]:
df

,0,processed,corrected
0,Hokkaido is in the northrn part of Japan.,hokkaido is in the northrn part of japan,hokkaido is in the northern part of japan
2,How about going to the movie on Satrday?,how about going to the movie on satrday,how about going to the movie on saturday
4,How am I goiing to protect my children now?,how am i goiing to protect my children now,how am i going to protect my children now
5,How are you getting along in your neww job?,how are you getting along in your neww job,how are you getting along in your new job
6,How are you getting along with your steudy?,how are you getting along with your steudy,how are you getting along with your study
...,...,...,...
638,I have got my guitar in the tunk of my car.,i have got my guitar in the tunk of my car,i have got my guitar in the trunk of my car
639,I have got plenty more whre that came from.,i have got plenty more whre that came from,i have got plenty more were that came from
640,I have just taled to Tom about that matter.,i have just taled to tom about that matter,i have just talked to tom about that matter
641,I have known her for more than twnty years.,i have known her for more than twnty years,i have known her for more than twenty years
642,I have livd here for more than three years.,i have livd here for more than three years,i have live here for more than three years

Interpretation:
* We can see that most of the spelling got corrected correctly
* But some were wrongly corrected (limitation of the package)

Way forward:
* We can try different spelling correction packages